### ISSUE TITLE
Java.io.FileNotFoundException is handled poorly

### ISSUE THREAD

**Issue by matthew-e-brown** [matthew-e-brown/COIS-2240-Assignment1#1]
Whenever the `data-export.csv` file is open in Excel, the `FileNotFoundException` is thrown.

This shouldn't be an issue, except for the fact that when this happens, the Scanner's *buffer* is not cleared. This causes yes another exception when re-run:

> ```
> Exception in thread "main" java.lang.StringIndexOutOfBoundsException: String index out of range: 0
>	at java.base/java.lang.StringLatin1.charAt(StringLatin1.java:47)
>	at java.base/java.lang.String.charAt(String.java:693)
>	at Main.getInput(Main.java:63)
>	at Main.main(Main.java:29)
>```

This error is thrown by this line; for some reason, the Scanner is reading in **some** junk value after having the error thrown. 
https://github.com/matthew-e-brown/COIS-2240-Assignment1/blob/167188ac6c486150b1697fcbcb01f61577b164e5/A1-Java/src/Main.java#L63

This only happens when `scan.newLine();` is not called after the exception is thrown. The sequence is as follows:
1. Choose `Export`;
2. `Java.io.FileNotFoundException` is thrown;
3. Try `Test`;
4. `Test` with a value of `5` runs fine, but upon returning to the main menu, the error above is thrown.

It all has to do with these two lines. Without them, the error occurs.
https://github.com/matthew-e-brown/COIS-2240-Assignment1/blob/167188ac6c486150b1697fcbcb01f61577b164e5/A1-Java/src/Main.java#L48-L49
The "handled poorly" comes from the fact that, with the two lines, an extra (**non-empty!**) line must be entered before returning to the main menu. I'm not sure how else to clear the Scanner's *"buffer."*

**Comment by matthew-e-brown** [comment]
I don't really care to fix this issue. The assignment is done with.
